# Site settings
title: Your awesome title
email: d2fong@uwaterloo.com
description: Site that hosts my portfolio and blog
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://dylanfong.com" # the base hostname & protocol for your site
github_username:  d2fong

# Build settings
markdown: kramdown
