markdown: rdiscount
pygments: true
permalink: /posts/:title
rdiscount:
  extensions: [smart]
exclude: [ Gemfile, Gemfile.lock, gems, _assets, bower_components ]
title : Dylan Fong
production_url : http://dylanfong.com
description: "d"
disqus_shortname: dlfn
analytics: UA-32899481-1
gauges: 50f2b533613f5d7c8000000c
author :
  name : Dylan Fong
  github : d2fong
  twitter : d2fong
  email: dylanfong93@gmail.com
