markdown: rdiscount
pygments: true
permalink: /posts/:title
rdiscount:
  extensions: [smart]
exclude: [ Gemfile, Gemfile.lock, gems, _assets, bower_components ]
title : Dylan Fong
production_url : http://carlosbecker.com
description: "Througths, flamewars, utilities, tutorials, codes, projects and other things by Carlos Alexandro Becker."
disqus_shortname: dlfn
analytics: UA-32899481-1
gauges: 50f2b533613f5d7c8000000c
author :
  name : Dylan Fong
  github : d2fong
  twitter : caarlos0
  email: dylanfong93@gmail.com
